Changed playbook to add appropriate environment variables and added smoke tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -418,6 +418,74 @@ jobs:
           template: basic_fail_1
           debug: false
 
+  smoke-test:
+    docker:
+      - image: python:3.9-alpine3.13
+    steps:
+      - checkout
+
+      - run:
+          name: Install aws-cli
+          command: | 
+             apk update && apk add --no-cache aws-cli
+
+      - run:
+          name: Install npm nodejs
+          command: | 
+             apk update && apk add --no-cache nodejs npm curl
+             apk update && apk add --no-cache openssh-client
+
+      - run:
+          name: Install ansible
+          command: |
+            apk update && apk add --no-cache ansible
+
+      - attach_workspace:
+          at: /tmp
+
+      - run:
+          name: Get backend url
+          command: |
+            BACKEND_IP=$(sed -n '/^\[WEB\]/{n;p;q}' /tmp/inventory.txt)
+            if [ -z "$BACKEND_IP" ]; then
+              echo "Error: BACKEND_IP is empty. Exiting."
+              exit 1
+            fi
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+
+      - run:
+          name: Backend smoke test.
+          command: |
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+  	          return 0
+            else
+  	          return 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+	          # Change this to 0 after the job fails
+              return 1
+            else
+              return 1
+            fi
+      - destroy-environment:
+          frontend-stackname: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
+          backend-stackname: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"  
+
+      - slack/notify:
+          event: fail
+          channel: "personal-projects"
+          mentions: "<@U06NLJDPAAG>"
+          template: basic_fail_1
+          debug: false
+
 workflows:
   default:
     jobs:
