Updated smoke tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -418,9 +418,11 @@ jobs:
             echo "API_URL = ${API_URL}" 
             if curl -v "${API_URL}/api/status" | grep "ok"
             then
-              return 0
+              echo "Backend smoke test succeeded."
+              exit 0
             else
-              return 1
+              echo "Backend smoke test failed."
+              exit 1
             fi
       - run:
           name: Frontend smoke test.
@@ -431,10 +433,10 @@ jobs:
             then
             # Change this to 0 after the job fails
               echo "failing for Screenshot"
-              return 1
+              exit 1
             else
               echo "Frontend deployment issue. Page not loaded successfully"
-              return 1
+              exit 1
             fi
       - destroy-environment:
           frontend-stackname: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
